title: Rubena Produkter AB
email: box@rubena.se
description: >- # this means to ignore newlines until "baseurl:"
  Rubena Produkter AB - Gjort för att hålla. Bred och hög kompetens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

language: sv-SE
lang: sv

logosmall: "/assets/images/logo/R.svg"

github_username: ubbe76

# Build settings
# theme: minima

plugins:
  # - jekyll-feed
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
